
services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  web:
    build: .
    command: >
      bash -c "
        python manage.py wait_for_db &&
        python manage.py makemigrations&&
        python manage.py migrate &&
        python manage.py fetch_data &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/DjangoProject3
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .env

volumes:
  postgres_data:
